### ISSUE TITLE
NullPointer exception during "Organize imports"

### ISSUE THREAD

**Issue by betasheet** [wangzw/CppStyle#10]
Hi there,

I've been experiencing a null pointer exception under some circumstances when I use the CDT's "Organize imports" function. It seems this function calls `ChangeFormatter.formatChangedCode(..)`, which calls `ClangFormatFormatter.format(String source, String path, IRegion[] regions)`.

In the case in which there are no changes that need to be formatted, this method in ClangFormatFormatter returns null [on line 226](https://github.com/wangzw/CppStyle/blob/master/plugin/src/org/wangzw/plugin/cppstyle/ClangFormatFormatter.java#L226), which causes a null pointer exception in the ChangeFormatter [on line 104](https://github.com/eclipse/cdt/blob/master/core/org.eclipse.cdt.core/src/org/eclipse/cdt/internal/formatter/ChangeFormatter.java#L104).

As a temporary fix, I was able to avoid the error by removing lines 225-227 in ClangFormatFormatter. However, I'm not sure whether this results in correct behavior in all scenarios.

Best,
Eric

**Comment by betasheet** [comment]
Hey, thanks for the quick bugfix update :)
It seems I've managed to conjure a NullPointerException at a slightly different location now:

```
Exception:java.lang.NullPointerException: null
	 at org.eclipse.cdt.internal.core.dom.rewrite.changegenerator.TextEditUtil.flatten(TextEditUtil.java:44)
	 at org.eclipse.cdt.internal.core.dom.rewrite.changegenerator.TextEditUtil.flatten(TextEditUtil.java:39)
	 at org.eclipse.cdt.internal.formatter.ChangeFormatter.formatChangedCode(ChangeFormatter.java:107)
	 at org.eclipse.cdt.internal.ui.refactoring.includes.IncludeOrganizer.organizeIncludes(IncludeOrganizer.java:331)
	 at org.eclipse.cdt.internal.ui.editor.OrganizeIncludesAction$1.runOnAST(OrganizeIncludesAction.java:83)
	 at org.eclipse.cdt.ui.text.SharedASTJob$1.runOnAST(SharedASTJob.java:74)
	 at org.eclipse.cdt.internal.core.model.ASTCache.runOnAST(ASTCache.java:219)
	 at org.eclipse.cdt.internal.ui.editor.ASTProvider.runOnAST(ASTProvider.java:336)
	 at org.eclipse.cdt.ui.text.SharedASTJob.run(SharedASTJob.java:71)
	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

From [TextEditUtil.java:44](https://github.com/eclipse/cdt/blob/master/core/org.eclipse.cdt.core/parser/org/eclipse/cdt/internal/core/dom/rewrite/changegenerator/TextEditUtil.java#L44), it seems that it is not expected that the TextEdit returned by `format(String source, String path, IRegion region)` may be null. I assume returning an empty TextEdit [here](https://github.com/wangzw/CppStyle/blob/master/plugin/src/org/wangzw/plugin/cppstyle/ClangFormatFormatter.java#L208) instead would fix the issue.

Thanks!
Eric

**Comment by betasheet** [comment]
Quick update: a "return new MultiTextEdit()" seems to fix it for me.

Btw - It may also be worth considering throwing AbortFormatting exceptions in erroneous cases, as the default formatter [does](https://github.com/eclipse/cdt/blob/master/core/org.eclipse.cdt.core/src/org/eclipse/cdt/internal/formatter/CCodeFormatter.java#L187).

**Comment by wangzw** [comment]
Hi, Have you tried the latest code, it suppose to be fixed in my last commit a few hours before.

**Comment by wangzw** [comment]
From the comments of **CodeFormatter**, It seems a bug of CDT. 


	/**
	 * Formats <code>source</code>, and returns a text edit that correspond to the difference
	 * between the given string and the formatted string. It returns null if the given string cannot
	 * be formatted.
	 * 
	 *......
	 */
	public abstract TextEdit format(int kind, String source, int offset, int length,
			int indentationLevel, String lineSeparator);

	/**
	 * Formats one or more regions of <code>source</code>, and returns an array of edits, one edit
	 * per region. If some of the regions cannot be formatted, the corresponding elements of
	 * the returned array will be <code>null</code>.
	 * 
	 *......
	 */
	public TextEdit[] format(int kind, String source, IRegion[] regions, String lineSeparator)

**Comment by betasheet** [comment]
I tried your update to 1.4.0.5 (again, thanks for this!) - that's what has moved the NullPointer a bit further down the road. You're right, the comments in CodeFormatter suggest that null would be a valid return value, but as I understand it, only if there was an erroneous condition (i.e. "if it _cannot_ be formatted", read: "if there was an error during formatting"). The ClangFormatFormatter also returns null if there just isn't anything that needs changing. That shouldn't be an erroneous condition, though, but a successful one with an empty set of changes.

That said, it would probably still make sense to file a bug for CDT's organize import tool. It shouldn't have to rely on successful formatting to organize the imports...

Does that make sense? :)

**Comment by wangzw** [comment]
Hi Eric

Anyway, returning **null** in **format()** means **NullPointerException** in CDT. I will return a **MultiTextEdit** instead of **null** to bypass this issue. 

Thanks for your feedback.

**Comment by betasheet** [comment]
Thanks, that seems to have solved the issue :)
