### ISSUE TITLE
*.hpp as header file format

### ISSUE THREAD

**Issue by grb19** [wangzw/CppStyle#13]
Hi,
We use your plugin for a project, that mainly uses *.hpp header files. And "modified" it to incorporate hpp header files for that purpose. As I assume, that we are not the only ones, that actually need this, I would suggest to add this within the CpplintChecker.java file.

greetings,
grb19

**Comment by wangzw** [comment]
Added, please give me feedback.

**Comment by grb19** [comment]
the modifications are the same we did, so it should work.

**Comment by schulmar** [comment]
Does that relate in some way to `Preferences -> C++ -> File Types`? Maybe the list there should be used instead of a hard coded one?

**Comment by grb19** [comment]
that would indeed be the better solution...

**Comment by wangzw** [comment]
The hard coded file types are default values. It can be changed in ``` Perference -> C/C++ -> Code Analysis-> Cpplint Issues``` globally or ```Project property -> C/C++ General -> Code Analysis -> Cpplint Issues``` for specific project.
