### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by rimathia** [wangzw/CppStyle#14]
Hi,

I'd really like to integrate cpplint into our eclipse setup at work. Unfortunately, I have no experience with Eclipse plugins and now I don't know how to search for the origin of the problem I'm encountering.

If you can point me to a general resource about troubleshooting eclipse plugins, that would already be great.

The installation of the plugin seems to have worked, there is an entry for CpplintIssues in Preferences/C/C++/Code Analysis.

If I do "run C/C++ code analysis" I get a "Launching cpplint" in the console. I haven't found any way of getting more information about the invocation of cpplint.

However, I get no issues from cpplint (as opposed to running it as an external program).

I can run cpplint.py as an external program:
Path\to\cpplint.py --extensions=cpp,hpp ${resource_loc}

Therefore cpplint by itself cannot be completely broken.

Here's the basic information about the eclipse installation (on windows):

Eclipse IDE for C/C++ Developers

Version: Luna Release (4.4.0)
Build id: 20140612-0600

**Comment by wangzw** [comment]
Hi 

To debug, you have to setup Eclipse plugin develop environment. You have to also install CDT source code.


By default, cpplint check is disabled, you can enable it in Eclipse "Preferences -> C/C++ -> CppStyle"

**Comment by rimathia** [comment]
Thanks for your swift reply. I'll have a look.

**Comment by speedogod** [comment]
Writing to an old thread since found no thread discussing the problem anywhere.
I found that in CppStyle in eclipse you have to give path to executable of cpplint. I created an executable using pyinstaller and now CppStyle works using cpplint in eclipse.
