### ISSUE TITLE
Running clang-format on save

### ISSUE THREAD

**Issue by jlisee** [wangzw/CppStyle#2]
I just gave this plugin a try with Eclipse Luna and clang-format 3.5, and it works great.  Thanks for releasing this.  I noticed you have an option to run cpplint on save.  Can we we add the option to run clang-format on save?  It's nice to just have formatting cleaned up as you go.

**Comment by wangzw** [comment]
Hi Joseph

Thanks for your feedback. I think it is OK to add this feature, but we also have to note that there may be some issues.

In my experience, format entire file is not recommended:
1) legacy code may not follow the styles, and we will not want to format unrelated code when you implement new feature. It will mess the commit.
2) clang-format is not smart enough, sometimes we have to manually format part of source code and do not want the clang-format to touch that part again. 
Before clang-format version 3.7, we have no way to disable clang-format for part of source code.

But things changed after clang-format 3.7, it supports to not format part of source code, and solved the above issues. And the feature you proposed become useful.

I will start working on this feature recently and thank you in advance if you can help to test it.

**Comment by wangzw** [comment]
Hi Joseph

This feature is ready, please update to CppStyle version 1.1.0.0 and have a try. 

Enjoy.

**Comment by jlisee** [comment]
Thanks for the really quick turn around.  Sorry I could not try this earlier, but I was too busy during the week.  I gave it a try and now when I save I get this message on the console:

    clang-format () does not exist

In the preferences panel I have "Run clang-format on save" checked and the "C**h**ang-format path:" (just noticed the spelling error, it should be C**l**ang-format) set to `/usr/bin/clang-format-3.5`

Looking at the code it looks like in the `runClangFormatOnSave` save function you are calling `getCpplintPath()` instead of `getClangFormatPath()`.

**Comment by jlisee** [comment]
I should mention that when I put in `/usr/bin/clang-format-3.5` for the cpplint path the code does get formatted on save (although there is window flickers), so it does appear to work except for the small configuration bug.

**Comment by wangzw** [comment]
Thanks very much for testing it. I have fixed the bug you found. Now you can update to version 1.1.0.0.

Hope this plugin could help you. Have a good day.

**Comment by jlisee** [comment]
That fixed it, thanks for the update.
