### ISSUE TITLE
Can't locate .clang-format file if project not on workspace folder

### ISSUE THREAD

**Issue by alexhausen** [wangzw/CppStyle#21]
My project is not inside the workspace folder, it is located at: `c:\projects\project1\` and I'm not supposed to change it.

The error message is the following:
`Cannot find clang-format configure file under any level parent directories of path (C:\Users\alex\workspace\a.cc).`
`Run clang-format with Google style by default.`

**Comment by dmjones** [comment]
I'm still getting this issue, when running version 1.5.0.0. Should it be fixed in that version?
