### ISSUE TITLE
Plugin builds unsigned lead to a security warning

### ISSUE THREAD

**Issue by jlisee** [wangzw/CppStyle#3]
With the latest update CppStyle is now working very well for me.  I was wondering if you could sign your plugin builds so that the eclipse security warning goes away. This guide appears to be a helpful how to on signing Eclipse plugins: https://nirmalsasidharan.wordpress.com/2010/09/04/signing_eclipse_plugins/

**Comment by wangzw** [comment]
Glad to hear that it works very well. 

Signing the plugin with a self-signed certificate is not an option. 
1) it cannot remove the warning dialog when someone install this plugin
2) this plugin is build on travis-ci.org automatically after the commit, it is not secure environment and the private key may leak.

So I'm wondering if I can publish this plugin to eclipse market place and get it signed by the Eclipse. I do not know if it will work.

**Comment by jlisee** [comment]
I think that would work well.  I was easily able to create an account on the eclipse [marketplace website](https://marketplace.eclipse.org), and other opensource plugins like [Vrapper](http://vrapper.sourceforge.net/home/) have [marketplace listings](https://marketplace.eclipse.org/content/vrapper).

I would really like to recommend the use of this plugin with my team, and having an official signed build from the marketplace would make that much easier.

**Comment by wangzw** [comment]
Hi

This plugin has already been listed in marketplace.
https://marketplace.eclipse.org/content/cppstyle

But as I guessed before, it is still using the current update site and keep unsigned. I'm trying to apply a free of charge code sign certificate for open source project from https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml

It may take several weeks since it is Chinese new year holiday now and the complicated process.

**Comment by jlisee** [comment]
Any word on the plugin signing?

**Comment by wangzw** [comment]
I cannot apply a free of charge code sign certificate for this project. So I will keep it unsigned. 

This project is under MIT license and it means that anyone can do almost anything with the source code including sign and redistributed it.

Have fun.
