### ISSUE TITLE
Characters are getting replaced by ?

### ISSUE THREAD

**Issue by moritzhoewer** [wangzw/CppStyle#39]
When I format code with clang-format through cppstyle, some characters get replaced by ? (Moritz Höwer --> Moritz H?wer) (Angle: 90° --> Angle: 90?).

This does not happen when I run clang-format directly (on the command line).

Seems to be a problem with character encoding...my Eclipse Workspace is set to UTF-8.

**Comment by VladimirMamonov** [comment]
I had a similar issue
I fixed it by adding the following line to eclipse.ini file:
-Dfile.encoding=UTF-8
