### ISSUE TITLE
ctrl-shift-f (format) vs ctrl-s (format on save) -- not same formatting

### ISSUE THREAD

**Issue by jmcarter17** [wangzw/CppStyle#41]
Weirdly, if we run clang-format on save, it formats correctly using our .clang-format file.
However, if we format by `ctrl-shift-f`, it formats using the default formatting (google?).

**Comment by pzfzpzudpzdzd** [comment]
Same here. With CppStyle 1.5.0.0.

Any ideas?

**Comment by MikeGitb** [comment]
Can confirm.

**Comment by p4nt3ro** [comment]
You have to make CppStyle the default formatter to get the `ctrl + shift + f` working.

From README:

> To enable CppStyle(clang-format) as default C/C++ code formatter, go to Preferences -> C/C++ -> Code Style -> Formatter page and switch "Code Formatter" from [built-in] to "CppStyle (clang-format)"

**Comment by dvileta** [comment]
I have set CppStyle as the default formatter but I also get this problem; using `ctrl + shift + f` yields a result which does not reflect the project's `.clang-format` config.
