### ISSUE TITLE
Website cppstyle.com is down (offline)

### ISSUE THREAD

**Issue by ChristianStadelmann** [wangzw/CppStyle#46]
I cannot reach cppstyle.com, neither from my web browser nor from Eclipse. As a result, I cannot update/install the CppStyle plugin.

This issue seems to be present for other people too: https://downforeveryoneorjustme.com/cppstyle.com

**Comment by ThomasLamsonFr** [comment]
I confirm that we're stuck in our company because of the website not being available anymore. If anyone has a mirror?
I tried to build the plugin from source, but it seems to run on old Java versions and I'm not an expert, so I cannot make it work.

**Comment by ChristianStadelmann** [comment]
https://xkcd.com/2347/ (Maybe Bejing, not Nebraska, according to the bio)

**Comment by ThomasLamsonFr** [comment]
I actually managed to get a copy of the built files as they were on the cppstyle.com website, from the gh-pages branch: https://github.com/wangzw/CppStyle/tree/gh-pages

I downloaded that git and uploaded it on a FTP of ours for it to be accessible from our various machines.
Might do for the time it takes to fix that issue!

By the way, thank you for your plugin @wangzw :100: , it's been very usefull to us!

**Comment by ChristianStadelmann** [comment]
> I actually managed to get a copy of the built files as they were on the cppstyle.com website, from the gh-pages branch: https://github.com/wangzw/CppStyle/tree/gh-pages

Thanks for the hint! In case someone else wonders how to use it, follow these steps:
1. Clone this git repository to your local computer, e.g. to `D:\OpenSource\CppStyle`
2. Check out the gh-pages branch by executing git checkout `gh-pages` in that folder
3. In _Eclipse_, open _Help → Install new Software → Add…_. Give it any name. For Location, you need to construct the path like this: Take the path from above, prefix it with `file:` and add the sub-folder `oxygen`. Example: `file:D:\OpenSource\CppStyle\oxygen`
4. After loading the data, check CppStyle and click Finish.


> By the way, thank you for your plugin @wangzw 💯 , it's been very usefull to us!

+1

**Comment by ChristianStadelmann** [comment]
The website is available again. Thanks!
