### ISSUE TITLE
Option to not refocus on console output

### ISSUE THREAD

**Issue by schulmar** [wangzw/CppStyle#5]
Everytime the formatter is used, the console displays

    Use clang-format configure file (...
    Run clang-format command: /usr/bin/clang-format -assume-filename=...

In itself this is not a problem, but the console gets the focus everytime this happens.
This means that the previously visible tab in the same group as the console (e.g. Problems, Tasks, ...)  becomes hidden by the console.

It would be nice if there was an option to disable the focus switch.

**Comment by wangzw** [comment]
Reasonable, I will add this feature this weekend.  Thanks for your feedback.

**Comment by wangzw** [comment]
In version 1.2.3.0, I add two options in console view's toolbar to enable active console view on standard output or error output.

![screen shot 2015-05-17 at 13 27 17](https://cloud.githubusercontent.com/assets/1254826/7669220/b0ec2b5c-fc98-11e4-8ade-66f673accced.png)
