### ISSUE TITLE
Have a key combo to invoke cpplint

### ISSUE THREAD

**Issue by massenz** [wangzw/CppStyle#6]
This is awesome!

Instructions are pretty clear, but it's not clear at all how do I invoke cpplint?
Cmd-Shift-i calls clang-format, that's clear enough, but what about cpplint?

Thanks in advance!

**Comment by massenz** [comment]
Ok - figured out: it can only be invoked on file-save.
It would be great if there were a key combo to make it run on demand (I really dislike stuff that runs automagically on file save).

Thanks!

**Comment by lostcontrol** [comment]
Same here. I was also looking for this in the menu, configuration settings, etc.

Why not call it when triggering "Run C/C++ Code Analysis"? This is how Metriculator does it and as far as I know this menu option is not a Metriculator specific one (but I might be wrong here).

**Comment by wangzw** [comment]
Hi Cyril

Your suggestion is good. And you are right about "Run C/C++ Code Analysis", it is the feature of "CDT StaticAnalysis" https://wiki.eclipse.org/CDT/designs/StaticAnalysis

I think it is good to integrate cpplint with "CDT StaticAnalysis" to take advantage of it. Eg. user can enable /disable cpplint on specific type of problems, customize scope(include/exclude patten) and launching. I think Metriculator did the same thing.

![screen shot 2015-06-15 at 09 51 04](https://cloud.githubusercontent.com/assets/1254826/8151660/3566c06a-1344-11e5-800e-0d7c5b4696b8.png)

**Comment by lostcontrol** [comment]
I'm now using 1.4.0.0 and cpplint integration is now much better. Thank you very much.

Still, the error markers are not removed when the problems are fixed. Looks like cppstyle only adds errors but never remove them. Do you want me to open a new issue for this?

**Comment by wangzw** [comment]
I just tried on my project. The error markers are removed from both editor and the problems window at the next time I trigger the cpplint (save the file after fixing the issue).

**Comment by lostcontrol** [comment]
Strange, error markers are not removed here!? Fixed warnings disappear from cpplint output (in the console view) but error markers are still there (in the editor and in the problem view). I'm using Eclipse Mars.

**Comment by wangzw** [comment]
Hi, I reproduce this issue, will fix it later.

**Comment by wangzw** [comment]
fixed, please update to version 1.4.0.2

**Comment by lostcontrol** [comment]
1.4.0.2 looks good. Thank you!
